matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "3.5"
    - os: linux
      dist: trusty
      language: python
      python: "3.6"
      
cache:
  pip: true

install:
  - pip install -r requirements-dev.txt

script:
    - python -m compileall py/*.py
    - flake8 py/*.py
    - codespell py/*.py
    - codespell js/*.js
